version: '3'
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
#      - .:/usr/share/nginx/html
#     - ./nginx/sites/site.conf:/etc/nginx/sites/available/default.conf
     - .:/var/www
    links:
     - phpfpm
     
#this shit doesn't work, tho that'k ok for now
  phpfpm:
    image: "php:7-fpm"
    ports:
      - "9000:9000" 
